/*
Copyright © contributors to CloudNativePG, established as
CloudNativePG a Series of LF Projects, LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

package postgres

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
	"time"
)

func TestControlFileGolden(t *testing.T) {
	// Generated by initdb; the identifiers are the ones pg_controldata printed
	for file, want := range map[string]uint64{
		"pg_control_14": 7690613496862998543,
		"pg_control_17": 7690613503764492303,
	} {
		t.Run(file, func(t *testing.T) {
			raw, err := os.ReadFile(filepath.Join("testdata", file))
			if err != nil {
				t.Fatal(err)
			}
			controlFile, err := parseControlFile(raw)
			if err != nil {
				t.Fatal(err)
			}
			if got := controlFile.SystemIdentifier(); got != want {
				t.Fatalf("system identifier %d, want %d", got, want)
			}

			controlFile.SetSystemIdentifier(42)
			reparsed, err := parseControlFile(controlFile.raw)
			if err != nil {
				t.Fatalf("the rewritten control file has no valid CRC: %v", err)
			}
			if reparsed.crcOffset != controlFile.crcOffset || reparsed.SystemIdentifier() != 42 {
				t.Fatalf("unexpected rewrite: offset %d/%d, id %d",
					reparsed.crcOffset, controlFile.crcOffset, reparsed.SystemIdentifier())
			}
		})
	}
}

func TestControlFileWrite(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("testdata", "pg_control_14"))
	if err != nil {
		t.Fatal(err)
	}
	pgData := t.TempDir()
	if err := os.MkdirAll(filepath.Join(pgData, "global"), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(pgData, pgControlFile), raw, 0o600); err != nil {
		t.Fatal(err)
	}

	controlFile, err := ReadControlFile(pgData)
	if err != nil {
		t.Fatal(err)
	}
	controlFile.SetSystemIdentifier(7)
	if err := controlFile.Write(pgData); err != nil {
		t.Fatal(err)
	}
	reread, err := ReadControlFile(pgData)
	if err != nil {
		t.Fatal(err)
	}
	if reread.SystemIdentifier() != 7 {
		t.Fatalf("system identifier %d, want 7", reread.SystemIdentifier())
	}
}

func TestControlFileCorrupted(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("testdata", "pg_control_14"))
	if err != nil {
		t.Fatal(err)
	}
	raw[20] ^= 0xFF
	if _, err := parseControlFile(raw); err == nil {
		t.Fatal("a corrupted control file must be rejected")
	}
}

func TestNewSystemIdentifier(t *testing.T) {
	now := time.Unix(1_790_000_000, 123_456_000)
	id := NewSystemIdentifier(now, 0x1234)
	if id>>32 != 1_790_000_000 {
		t.Fatalf("seconds not in the high bits: %x", id)
	}
	if (id>>12)&0xFFFFF != 123456 {
		t.Fatalf("microseconds not in the middle bits: %x", id)
	}
	if id&0xFFF != 0x234 {
		t.Fatalf("pid not in the low bits: %x", id)
	}
}

func TestLSN(t *testing.T) {
	value, err := ParseLSN("1/A0000028")
	if err != nil || value != 0x1_A000_0028 {
		t.Fatalf("ParseLSN = %x, %v", value, err)
	}
	for _, invalid := range []string{"", "12", "x/1", "1/zz"} {
		if _, err := ParseLSN(invalid); err == nil {
			t.Fatalf("ParseLSN(%q) must fail", invalid)
		}
	}

	cases := []struct {
		a, b string
		want bool
	}{
		{"0/10", "", true},
		{"0/10", "0/9", true},
		// A string comparison would get this one wrong
		{"0/10000000", "0/F000000", true},
		{"1/0", "0/FFFFFFFF", true},
		{"0/10", "0/10", false},
		{"0/9", "0/10", false},
	}
	for _, c := range cases {
		got, err := LSNGreater(c.a, c.b)
		if err != nil || got != c.want {
			t.Fatalf("LSNGreater(%q, %q) = %v, %v", c.a, c.b, got, err)
		}
	}
}

func TestParseHistorySwitchPoint(t *testing.T) {
	content := "1\t0/3000148\tno recovery target specified\n\n" +
		"2\t0/5A01D90\tafter LSN \"0/5A01D18\"\n"
	got, err := parseHistorySwitchPoint(content)
	if err != nil || got != "0/5A01D90" {
		t.Fatalf("parseHistorySwitchPoint = %q, %v", got, err)
	}
	if _, err := parseHistorySwitchPoint("\n# comment\n"); err == nil {
		t.Fatal("an empty history must be rejected")
	}
	if _, err := parseHistorySwitchPoint("1\tnot-an-lsn\treason\n"); err == nil {
		t.Fatal("an invalid switch point must be rejected")
	}
}

func TestRemoveRecoverySettings(t *testing.T) {
	file := filepath.Join(t.TempDir(), "postgresql.auto.conf")
	content := strings.Join([]string{
		"# Do not edit this file manually!",
		"work_mem = '8MB'",
		"primary_conninfo = 'host=source'",
		"primary_slot_name = 'cnpgsub_1_phys'",
		"recovery_target_lsn = '0/3000000'",
		"  recovery_target_action=promote",
		"recovery_target_timeline = 'latest'",
		"restore_command = 'cp %f %p'",
		"",
	}, "\n")
	if err := os.WriteFile(file, []byte(content), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := RemoveRecoverySettings(file); err != nil {
		t.Fatal(err)
	}
	result, err := os.ReadFile(file)
	if err != nil {
		t.Fatal(err)
	}
	want := "# Do not edit this file manually!\nwork_mem = '8MB'\nrestore_command = 'cp %f %p'\n"
	if string(result) != want {
		t.Fatalf("got:\n%s\nwant:\n%s", result, want)
	}

	if err := RemoveRecoverySettings(filepath.Join(t.TempDir(), "missing.conf")); err != nil {
		t.Fatalf("a missing file is not an error: %v", err)
	}
}

func TestPgCreateSubscriberArgs(t *testing.T) {
	plan := CreateSubscriberPlan{
		ObjectPrefix:    "cnpgsub_abcd1234_",
		RecoveryTimeout: time.Hour,
		SourceConnString: func(database string) string {
			return "host=source passfile=/p dbname=" + database
		},
	}
	plan.Databases = []CreateSubscriberDatabase{
		{Name: "app", OID: 16384, Object: plan.ObjectName(16384)},
		{Name: "crm", OID: 16390, Object: plan.ObjectName(16390)},
	}

	args := plan.PgCreateSubscriberArgs("/pgdata", "/run")
	joined := strings.Join(args, " ")
	for _, want := range []string{
		"--pgdata /pgdata",
		"--publisher-server host=source passfile=/p dbname=app",
		"--recovery-timeout 3600",
		"--database app --publication cnpgsub_abcd1234_16384 " +
			"--subscription cnpgsub_abcd1234_16384 --replication-slot cnpgsub_abcd1234_16384",
		"--database crm --publication cnpgsub_abcd1234_16390",
	} {
		if !strings.Contains(joined, want) {
			t.Fatalf("missing %q in %v", want, args)
		}
	}
	// The generated names are the only ones allowed: --all would not accept them
	if slices.Contains(args, "--all") {
		t.Fatal("--all must never be used")
	}
}

func TestPgBaseBackupSlotOptions(t *testing.T) {
	options := pgBaseBackupSlotOptions("host=source", "/data", "", "cnpgsub_x_phys")
	joined := strings.Join(options, " ")
	for _, want := range []string{"--checkpoint=fast", "-X stream", "-C -S cnpgsub_x_phys"} {
		if !strings.Contains(joined, want) {
			t.Fatalf("missing %q in %v", want, options)
		}
	}
}

func TestCreateSubscriberMarker(t *testing.T) {
	pgData := t.TempDir()
	marker, err := ReadCreateSubscriberMarker(pgData)
	if err != nil || marker != nil {
		t.Fatalf("no marker expected: %v, %v", marker, err)
	}

	want := CreateSubscriberMarker{
		Engine:        CreateSubscriberEngineEmulated,
		Major:         14,
		ConsistentLSN: "0/3000148",
		PromotedLSN:   "0/30001C0",
		Databases:     []CreateSubscriberDatabase{{Name: "app", OID: 16384, Object: "cnpgsub_x_16384"}},
	}
	if err := WriteCreateSubscriberMarker(pgData, want); err != nil {
		t.Fatal(err)
	}
	got, err := ReadCreateSubscriberMarker(pgData)
	if err != nil {
		t.Fatal(err)
	}
	if got.PromotedLSN != want.PromotedLSN || got.Databases[0].Object != "cnpgsub_x_16384" {
		t.Fatalf("unexpected marker %+v", got)
	}
}
